refartor envia endpoint
AlhuayOscar/Lachoco-Back pull request #77
Opened 2024-08-28 22:47 UTC by JDRengifo

2024-08-28 23:09 UTC, Yohaan2 requested changes

2024-08-28 23:09 UTC, Yohaan2 commented on .env.example
> +
Eliminar valores de variables de entorno

2024-08-28 23:09 UTC, Yohaan2 commented on .env.example
> +# CLAVE_CREAR_BDD = 123456
Eliminar modificacion

2024-08-28 23:09 UTC, Yohaan2 commented on src/config/typeOrm.ts
>  };
quitar comentarios

2024-08-28 23:09 UTC, Yohaan2 commented on src/config/typeOrm.ts
> +  ssl: false,
Dejar el ssl en true

2024-08-29 00:00 UTC, JDRengifo commented on src/config/typeOrm.ts
> +  ssl: false,
ya se actualizo

2024-08-29 00:00 UTC, JDRengifo commented on .env.example
> +# CLAVE_CREAR_BDD = 123456
ya se actualizo

2024-08-29 00:02 UTC, JDRengifo commented on src/config/typeOrm.ts
> +  ssl: false,
ya se actualizo

2024-08-29 01:43 UTC, Yohaan2 approved these changes

2024-08-29 01:44 UTC, merged